# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-Bzip2
version:      1.1
version_from: lib/POE/Filter/Bzip2.pm
installdirs:  site
requires:
    Carp:                          0
    Compress::Bzip2:               2.08
    POE:                           0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
