author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Filter-Bzip2
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Compress::Bzip2: 2.08
  POE: 0.38
version: 1.51
